name: first-time-setup
run-name: first-time setup

on:
  # run if user manually requests it
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  first-time-setup:
    # only run on user instance of template, not template itself
    if: github.repository != 'greenelab/lab-website-template'
    runs-on: ubuntu-latest
    
    steps:
      - name: Debug dump
        uses: crazy-max/ghaction-dump-context@v2

      # set up gh-pages branch
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          
      - name: Clear gh-pages branch
        run: |
          git rm -r .
          git clean -fxd
          echo "<meta http-equiv=\"refresh\" content=\"0; URL=../\" />" >> index.html
          echo "" >> .nojekyll
          
      - name: Commit empty gh-pages branch
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Clean gh-pages branch"

      # set up main branch
      - name: Checkout main branch
        uses: actions/checkout@v4
        
      - name: Clean up template files
        run: |
          rm .github/workflows/first-time-setup.yaml
          rm .github/workflows/versioning.yaml
          rm .github/FUNDING.yml
          rm .github/ISSUE_TEMPLATE/*
          rm .github/PULL_REQUEST_TEMPLATE.md
          rm .readthedocs.yaml
          rm CITATION.cff
          rm CODE_OF_CONDUCT.md
          rm CONTRIBUTING.md
          rm SECURITY.md
          rm .gitignore
          rm LICENSE
          rm .editorconfig
          rm .gitattributes
          rm .github/workflows/on-schedule.yaml

      - name: Get repository name
        id: repository-name
        run: echo "name=$(echo '${{ github.repository }}' | cut -d'/' -f2)" >> "$GITHUB_OUTPUT"

      - name: Update README.md
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require("fs");
            let readme = fs.readFileSync("README.md").toString();
            readme = readme.replace(/greenelab-template/, "${{ steps.repository-name.outputs.name }}");
            fs.writeFileSync("README.md", readme);

      - name: Update Jekyll config
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require("fs");
            let config = fs.readFileSync("_config.yaml").toString();
            config = config.replace(/TITLE_FOR_YOUR_WEBSITE/, "${{ steps.repository-name.outputs.name }}");
            fs.writeFileSync("_config.yaml", config);

      - name: Update index.md
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require("fs");
            let config = fs.readFileSync("index.md").toString();
            config = config.replace(/SHORT_DESCRIPTION_OF_YOUR_WEBSITE/, "${{ steps.repository-name.outputs.name }}");
            fs.writeFileSync("index.md", config);

      - name: Commit template cleanup
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Initial commit after template cleanup"